http_port 3128
http_access allow all 

# ICAP configuration for reqmod and respmod
# You need to replace 'icap://icap.example.com/reqmod' and 'icap://icap.example.com/respmod'
# with the actual addresses of your ICAP server.

icap_enable on

# Increase ICAP timeouts to prevent "options fetch failure"
icap_connect_timeout 10 seconds
icap_io_timeout 30 seconds
icap_service_failure_limit -1
icap_service_revival_delay 30
icap_preview_enable off
icap_preview_size 1024
adaptation_send_client_ip on
adaptation_send_username on

# Request Modification (reqmod)
icap_service reqmod_service reqmod_precache bypass=1 icap://icap-server:1344/reqmod
adaptation_access reqmod_service allow all

debug_options 90,9

# Response Modification (respmod)
#icap_service respmod_service respmod_precache bypass=0 icap://icap-server:1344/respmod
#adaptation_access respmod_service allow all 